### ISSUE TITLE
Default tolerance is 4 (and not 2, as specified in the README file)

### ISSUE THREAD

**Issue by pvdb** [michaeledgar/profanalyzer#1]
Hi Michael,

Love this gem of a gem! :-)

Small issue: the README claims that the default tolerance is 2, but if I interpret the source code correctly, it's actually 4?!?

Also, it would be useful to have a getter method on the Profanalyzer class to query for the current tolerance level, which at the moment appears to be completely private.

I'll submit a pull request for these two issues... thanks for your consideration!

Peter

**Comment by michaeledgar** [comment]
Merged in your branch – thanks for your contribution!
