### ISSUE TITLE
Adding to the list

### ISSUE THREAD

**Issue by bensie** [michaeledgar/profanalyzer#3]
Is there any way to add custom words to the profanity list?  It seems it's currently locked down to the YAML file included in the gem.

**Comment by michaeledgar** [comment]
Thanks for the suggestion! Added a patch today, with a bit more testing I'll push out a new gem version this weekend or so.

Thanks!

**Comment by jeremyruppel** [comment]
Hey @michaeledgar, great work here! Any chance this could make its way up to rubygems soon?
